# botapp/remedies.py

remedies = {
    "cold": "Drink warm fluids, rest, and take vitamin C.",
    "fever": "Drink plenty of water, rest, and take paracetamol if needed.",
    "stomach pain": "Avoid spicy food, drink ginger tea, and rest.",
    "headache": "Rest in a quiet room, hydrate, and take mild painkillers if necessary.",
    "cough": "Drink warm water, honey, and ginger tea. Avoid cold drinks.",
    "sore throat": "Gargle warm salt water, drink warm fluids, and rest your voice.",
    "back pain": "Apply heat or ice, do gentle stretches, and avoid heavy lifting.",
    "allergy": "Avoid allergens, take antihistamines, and keep your environment clean.",
    "diarrhea": "Drink plenty of fluids, eat bland foods, and avoid dairy.",
    "constipation": "Increase fiber intake, drink plenty of water, and exercise regularly.",
    "flu": "Rest, drink fluids, and consider antiviral medication if prescribed.",
    "insomnia": "Maintain a regular sleep schedule, avoid caffeine late, and create a relaxing bedtime routine.",
    "anxiety": "Practice deep breathing, mindfulness, and seek professional help if severe.",
    "dehydration": "Drink water and oral rehydration solutions, avoid alcohol and caffeine.",
    "acidity": "Avoid spicy and oily food, eat smaller meals, and drink plenty of water.",
    "migraine": "Rest in a dark room, stay hydrated, and take prescribed medication if needed.",
    "hypertension": "Reduce salt intake, exercise regularly, and monitor blood pressure.",
    "hypotension": "Drink more fluids, eat small frequent meals, and avoid standing suddenly.",
    "diabetes": "Monitor blood sugar, follow a balanced diet, and take prescribed medication.",
    "obesity": "Exercise regularly, follow a healthy diet, and avoid sugary drinks.",
    "asthma": "Avoid triggers, take inhalers as prescribed, and monitor breathing.",
    "bronchitis": "Rest, stay hydrated, and avoid smoke and pollutants.",
    "pneumonia": "See a doctor, take prescribed antibiotics, and rest.",
    "ear pain": "Apply a warm compress, avoid inserting objects into ears, and consult a doctor if severe.",
    "eye strain": "Take regular breaks from screens, adjust lighting, and practice eye exercises.",
    "toothache": "Rinse with warm salt water, avoid hot/cold drinks, and see a dentist if persistent.",
    "gum bleeding": "Maintain oral hygiene, brush gently, and consult a dentist if needed.",
    "hair fall": "Eat a protein-rich diet, avoid excessive heat styling, and manage stress.",
    "dandruff": "Use anti-dandruff shampoo, keep scalp clean, and avoid scratching.",
    "eczema": "Moisturize regularly, avoid irritants, and use prescribed creams.",
    "psoriasis": "Moisturize, avoid triggers, and use prescribed medications.",
    "acne": "Cleanse face gently, avoid oily products, and follow a dermatologist’s advice.",
    "cold sores": "Apply antiviral cream, avoid touching the sores, and maintain hygiene.",
    "chickenpox": "Avoid scratching, keep skin clean, and consult a doctor for relief.",
    "measles": "Rest, stay hydrated, and follow doctor’s advice.",
    "mumps": "Rest, drink fluids, and apply warm/cold compress for pain relief.",
    "typhoid": "Consult a doctor for antibiotics, drink fluids, and follow dietary advice.",
    "cholera": "Drink oral rehydration solution and consult a doctor immediately.",
    "hepatitis": "Rest, avoid alcohol, and follow doctor’s prescribed treatment.",
    "jaundice": "Drink plenty of fluids, rest, and avoid oily food.",
    "urinary tract infection": "Drink plenty of water, maintain hygiene, and consult a doctor for antibiotics.",
    "kidney stones": "Drink water, avoid salt, and consult a doctor for treatment.",
    "kidney infection": "Take prescribed antibiotics, rest, and drink fluids.",
    "liver disease": "Avoid alcohol, follow a healthy diet, and take prescribed medications.",
    "anemia": "Eat iron-rich foods, take supplements if prescribed, and monitor blood levels.",
    "vitamin deficiency": "Eat a balanced diet with required vitamins, and consider supplements.",
    "osteoporosis": "Consume calcium and vitamin D, exercise, and avoid smoking.",
    "arthritis": "Exercise gently, maintain weight, and use prescribed anti-inflammatory medications.",
    "joint pain": "Apply heat/cold compress, rest, and take pain relief if needed.",
    "muscle pain": "Stretch, rest, and apply warm compress.",
    "sprain": "Rest, ice, compression, and elevate the affected area.",
    "fracture": "Immobilize, see a doctor immediately, and follow medical treatment.",
    "burns": "Cool the burn with water, apply sterile dressing, and seek medical care for severe burns.",
    "cuts": "Clean with antiseptic, cover with a bandage, and monitor for infection.",
    "nosebleed": "Sit upright, pinch nostrils, and apply cold compress.",
    "dizziness": "Sit or lie down, drink fluids, and rest.",
    "nausea": "Sip water, eat bland foods, and rest.",
    "vomiting": "Drink fluids, eat small meals, and rest.",
    "heartburn": "Avoid spicy foods, eat smaller meals, and stay upright after eating.",
    "gas": "Avoid carbonated drinks, eat slowly, and take gentle exercise.",
    "bloating": "Eat slowly, avoid gas-producing foods, and drink water.",
    "constipation": "Increase fiber, hydrate, and exercise regularly.",
    "hemorrhoids": "Use warm sitz baths, avoid straining, and eat fiber-rich foods.",
    "varicose veins": "Exercise, elevate legs, and wear compression stockings.",
    "cold feet": "Keep feet warm, improve circulation, and exercise.",
    "sleep apnea": "Maintain healthy weight, avoid alcohol, and consult a doctor.",
    "snoring": "Sleep on your side, avoid alcohol before bed, and maintain healthy weight.",
    "depression": "Seek professional help, practice self-care, and maintain social support.",
    "stress": "Practice relaxation techniques, exercise, and maintain work-life balance.",
    "panic attack": "Practice deep breathing, grounding techniques, and seek help if severe.",
    "hypothyroidism": "Take prescribed medication, eat balanced diet, and follow doctor’s advice.",
    "hyperthyroidism": "Follow prescribed treatment, avoid stimulants, and monitor symptoms.",
    "menstrual cramps": "Apply heat, take painkillers, and rest.",
    "pregnancy nausea": "Eat small meals, avoid strong smells, and stay hydrated.",
    "morning sickness": "Eat ginger, small frequent meals, and rest.",
    "urinary incontinence": "Practice pelvic exercises, avoid bladder irritants, and consult a doctor.",
    "skin rash": "Avoid irritants, keep skin clean, and use prescribed creams.",
    "ringworm": "Apply antifungal cream, keep area dry, and maintain hygiene.",
    "athlete's foot": "Keep feet dry, use antifungal powder, and avoid walking barefoot in public areas.",
    "fungal nail infection": "Use antifungal treatment, keep nails trimmed, and maintain hygiene.",
    "cold feet": "Keep feet warm, exercise to improve circulation, and avoid tight shoes.",
    "heat stroke": "Move to cool place, hydrate, and seek medical attention immediately.",
    "hypothermia": "Warm gradually, remove wet clothes, and seek medical care.",
    "food poisoning": "Drink fluids, rest, and consult a doctor if severe.",
    "motion sickness": "Sit facing forward, avoid heavy meals, and use anti-nausea medication if needed.",
    "jet lag": "Adjust sleep schedule, stay hydrated, and get sunlight exposure.",
    "eye infection": "Maintain hygiene, avoid touching eyes, and consult a doctor if severe.",
    "pink eye": "Use prescribed eye drops, maintain hygiene, and avoid touching eyes.",
    "conjunctivitis": "Apply prescribed drops, avoid sharing towels, and maintain hygiene.",
    "ear infection": "Take prescribed antibiotics, avoid water in ears, and rest.",
    "tinnitus": "Avoid loud noise, manage stress, and consult a doctor.",
    "ringing in ears": "Reduce exposure to loud sounds, manage stress, and consult a doctor."
}
